<div id="loguear">
  <h1 class="center">
    Inciar sesión
  </h1>
  <nav class="container-center">
    <div class="col-xs-4 border">
      <form action="" method="post" class="form-horizontal">
        <div class="form-group">
          <div class="col-xs-3">
            <label for="user_name">Usuario</label>
          </div>
          <div class="col-xs-9">
            <input type="text" name="user_name" id="user_name" class="form-control" placeholder="Usuario">
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-3">
            <label for="password">Contraseña</label>
          </div>
          <div class="col-xs-9">
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-default">Entrar</button>
          </div>
        </div>
      </form>
      <?php if ($this->error):?>
      <p class="bg-danger">
        <span class="glyphicon glyphicon-info-sign"></span>
        <?php echo $this->error;?>
      </p>
      <?php endif;?>
      <div class="">
        <button onclick="loguear()" class="btn btn-primary fb_button">
          Iniciar Sesión con Facebook
        </button>
        <a href="/task/usuario/twitterConnect" class="btn btn-primary tw_button">
          Iniciar Sesión con Twitter
        </a>
      <fb:login-button scope="public_profile,email" style="display:none;">
      </fb:login-button>
      <div>
      <div id="status">
      </div>
    </div>
  </nav>
<script type="text/javascript">
  function statusChangeCallback(response) {

    if (response.status === 'connected') {
      testAPI();
    } else if (response.status === 'not_authorized') {
      // TODO: throw message
    } else {
      FB.login(function(response) {
        if (response.authResponse) {
          testAPI();
        }
      });
    }
  }

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '120566414959281',
      cookie     : true, 
      xfbml      : true,
      version    : 'v2.4'
    });
  };

  function loguear() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  function testAPI() {
    FB.api('/me', function(response) {

      $.post(
        base_url + '/usuario/fblogin', 
        {
          fb_key  : response.id,
          fb_name : response.name
        },
        function(ret) {
          if (ret.response) {
            window.location = ret.redirect;
          }
        },
        'json'
      );
    });
  }
</script>
</div>