<div id="loguear">
  <h1 class="center">
    Inciar sesión
  </h1>
  <nav class="container-center">
    <div class="col-xs-4 border">
      <form action="" method="post" class="form-horizontal">
        <div class="form-group">
          <div class="col-xs-3">
            <label for="user_name">Usuario</label>
          </div>
          <div class="col-xs-9">
            <input type="text" name="user_name" id="user_name" class="form-control" placeholder="Usuario">
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-3">
            <label for="password">Contraseña</label>
          </div>
          <div class="col-xs-9">
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-default">Entrar</button>
          </div>
        </div>
      </form>
      <?php if ($this->error):?>
      <p class="bg-danger">
        <span class="glyphicon glyphicon-info-sign"></span>
        <?php echo $this->error;?>
      </p>
      <?php endif;?>
      <div class="">
      <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
      </fb:login-button>
      <div>
      <div id="status">
      </div>
    </div>
  </nav>
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {

    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '120566414959281',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.4' // use version 2.2
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    FB.api('/me', function(response) {

      $.post(
        base_url + '/usuario/fblogin', 
        {
          fb_key  : response.id,
          fb_name : response.name
        }
      ).done(function(response) {
        if (response == "true") {

          window.location = base_url + '/index';
        }
        console.log(response);
      });
      
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>
</div>