<style type="text/css">
	.user_photo {
	    border-radius: 100%;
	}

</style>
<div class="container">
	<h1>Mi Cuenta</h1>

	<div class="row">
	  <div class="col-xs-4">
		<form method="post">
		  <div class="form-group">
		    <label for="usuario">Usuario</label>
		    <input type="text" class="form-control" id="usuario" placeholder="Usuario" readonly="readonly" value="<?php echo $this->user->getName()?>" />
		  </div>
		  <div class="form-group">
		    <label for="mail">Mail</label>
		    <input type="email" name="mail" class="form-control" id="mail" placeholder="Mail" value="<?php echo $this->user->getMail()?>">
		  </div>
		  <div class="form-group">
		    <label for="password">Contraseña</label>
		    <input type="password" name="password" class="form-control" id="password" placeholder="Contraseña">
		  </div>
		  <div class="form-group">
		    <label for="confirm_password">Confirmar</label>
		    <input type="password" name="repeat_password" class="form-control" id="confirm_password" placeholder="Confirmar">
		  </div>
		  
		  <button type="submit" class="btn btn-primary right">
		  	Guardar 
		  	<span class="glyphicon glyphicon-chevron-right"></span>
	  	  </button>
		</form>
	  </div>
	  <div class="col-xs-4">
		<?php if ($this->user != null):?>
			<a href="/task/usuario/profile" data-bypass="data-bypass">
			<?php if ($this->user->getFbKey()): ?>
				<img src="//graph.facebook.com/<?php echo $this->user->getFbKey();?>/picture?height=500" class="user_photo">
			<?php endif; ?>
		<?php endif; ?>
	  </div>
	</div>

</div>