<div id="registrar">
	<h1 class="center">
		Registro de usuario
	</h1>
	<form action="<?php echo $this->baseUrl;?>/usuario/registrar" method="post">
		<div>
			<label for="email">Correo Electrónico:</label>
			<input id="email" type="text" name="email">
		</div>
		<div>
			<label for="user_name">Nombre de Usuario:</label>
			<input id="user_name" type="text" name="user_name">
		</div>
		<div>
			<label for="password">Contraseña:</label>
			<input id="password" type="password" name="password">
		</div>
		<div>
			<label for="repeat_password">Repetir:</label>
			<input id="repeat_password" type="password" name="repeat_password">
		</div>
		<input type="submit" value="Registrar" class="boton_gris" />
	</form>
</div>
<?php if ($this->error):?>
<div class="error">
	<img alt="Error" src="<?php echo $this->webApp . '/img/error.gif';?>">
	<?php echo $this->error;?>
</div>
<?php endif;?>