<?php if (isset($this->task)) :?>
<?php echo $this->headLink()
              ->prependStylesheet($this->webApp . '/css/task/view.css');?>
	<div id="view_task">
		<?php $status = $this->task->getStatus();
		if ($status) {
			switch($status->getDescripcion()) {
				case 'Openned':
					$class = 'glyphicon-record';
					break;
				case 'Started':
					$class = 'glyphicon-play-circle';
					break;
				case 'Done':
					$class = 'glyphicon-ok-circle';
					break;
			}
		} else {
			$class = 'glyphicon-record';
		}?>
		<div>
		<a href="#" class="left show_status glyphicon <?php echo $class?>" value="<?php echo $this->task->getStatusId()?>" ></a>
		<form class="title_view_form left ">
			<textarea name="title" class="autosize" ><?php echo $this->task->getTitle();?></textarea>
		</form>
		<a href="#" class="remove glyphicon glyphicon-trash" value="<?php echo $this->task->getId()?>" ></a>
		</div>
		<div class="asign">
			<span>
				Asignados:
			</span>
			<input type="text" name="asign" placeholder="Ingrese usuario" class="asign_user form-control">
			<?php $users = $this->task->getUsers();?>
			<ul class="user_asigned">
			<?php foreach ($users as $user):?>
				<li>
					<a href="#" class="remove_user_asign glyphicon glyphicon-remove-circle"></a>
					<span class="user_name"><?php echo $user;?></span>
				</li>
			<?php endforeach;?>
			</ul>
		</div>
		<script type="text/javascript">
$(document).ready(function() {
	setTimeout(function() {
			$('.autosize').autosize();
	},1000);

	// AUTOCOMPLETE ASIGN USERS IN DETAILS
	$(".detail_task .asign_user").autocomplete({
		source : function(request, response) {

			discard = [];
			$('.user_asigned li').each(function(index,element) {
				discard[discard.length] = $(element).html();
			}); 
			$.ajax({
				url : base_url + '/usuario/search',
				data : {
					name : request.term,
					discard: discard
				},
				dataType : 'json',
				type : 'GET',
				success : function(data) {
					ultimos_buscados = data;
					response($.map(data, function(item) {
						return {
							label : item.name,
							value : item.id
						};
					}));
				},
				error : function(request, status, error) {
					alert(error);
				}
			});
		},
		minLength : 1,
		focus: function(event,ui) {
			return false;
		},
		select : function(event, ui) {
			abrir_cargando();

			$.post(
				base_url + '/task/asign', 
				{
					id : ultimo_selected_task,
					name: ui.item.label
				},
				'json'
			).done(function(response) {
				if (response) {
					$('.user_asigned').append(
						'<li>' +
							'<a href="#" class="remove_user_asign glyphicon glyphicon-remove-circle"></a>' + 
							'<span class="user_name">' +
								ui.item.label +
							'</span>' + 
						'</li>'
					);
					
					$(".detail_task .asign_user").val('');
					$('.tasks_list li[value="'+ ultimo_selected_task + '"] .task_users').append(
						'<a href="#' + ui.item.id + '" class="right user">' + ui.item.label + '</a>'
					);
				}
			}).fail(function() {
				
			}).always(function() {
				cerrar_cargando();
			});;
			return false;
		},
		response : function(event, ui) {
		}
	});
});

// CLICK REMOVE USER ASIGN
$('.remove_user_asign').on('click', function(e) {
		abrir_cargando();
		e.preventDefault();
		var _this = $(this);
		var user_name = _this.closest('li').find('.user_name').html();
		$.post(
			base_url + '/task/removeasign', 
			{
				id : ultimo_selected_task,
				name: user_name
			},
			'json'
		).done(function(response) {
			if (response) {
				_this.closest('li').remove();
				var task_users = $('.tasks_list li[value="'+ ultimo_selected_task + '"] .task_users a');
				task_users.each(function(index, element) {
					console.log(element);
					if ($(element).html() == user_name) {
						$(element).remove();
					}
				});
			}
		}).fail(function() {
			
		}).always(function() {
			cerrar_cargando();
		});;
		return false;
});
		</script>
	</div>
<?php endif;?>