<div id="div_form_project">
	<style>
		#form_create_project .form-control {
			margin-bottom: 10px;
		}
		#form_create_project h1 {
			font-size: 18px;
		}
		#form_create_project .btn-primary {
			float: right;
		}
	</style>
	<form id="form_create_project">
	<h1>Comenzar un proyecto:</h1>
	<input name="name" class="form-control" type="text" placeholder="Ingrese el proyecto"/>
	<button class="btn btn-primary" >Start a project</button>
	</form>
</div>