<div id="index">
	<div class="menu_left">
		<h1>MARCADOR DE TAREAS</h1>
		<div class="projects">
			<div class="user_logged">
				<div class="right">
				<?php if ($this->user != null):?>
				<?php echo $this->user->getName();?>
				<a class="glyphicon glyphicon-off" href="usuario/salir"></a>
				<?php endif;?>
				</div>
				<div class="clear"></div>
			</div>
			<div class="users_title" >
				Usuarios
				<span class="glyphicon glyphicon-plus btn" id="create_user"></span>
			</div>
			<ul class="users_list">
			<?php foreach ($this->users as $user):?>
				<li>
					<a href="#<?php echo $user->getName();?>" class="user" value="<?php echo $user->getId();?>">
						<?php echo $user->getName();?>
					</a>
					<span class="badge openned"><?php echo $user->getLastModified();?></span>
					<a href="#" class="edit_user" value="<?php echo $user->getId();?>">
						<span class="right glyphicon glyphicon-edit"></span>
					</a>
				</li>
			<?php endforeach;?>
			</ul>
			<div class="project_title" >
				<a href="#" class="title_my_projects">Mis Proyectos</a>
				<span class="glyphicon glyphicon-plus btn" id="create_project"></span>
			</div>
			<ul class="projects_list">
			<?php foreach ($this->projects as $project):?>
				<li>
					<a href="#<?php echo $project->getName();?>" class="project" value="<?php echo $project->getId();?>"><?php echo $project->getName();?></a>
					<?php $count_openned = $project->getCountOpenned();?>
					<?php if ($count_openned > 0) :?>
						<span class="badge openned"><?php echo $count_openned?></span>
					<?php else:?>
						<span class="badge closed"><?php echo $count_openned?></span>
					<?php endif;?>
					<a href="#" class="edit_project" value="<?php echo $project->getId();?>"><span class="right glyphicon glyphicon-edit"></span></a>
				</li>
			<?php endforeach;?>
			</ul>
		</div>
		
	</div>
	<div class="menu_right">
		<form class="search_form">
			<input type="text" name="title" placeholder="Buscar una tarea" class="search_task form-control">
			<span class="glyphicon glyphicon-search"></span>
		</form>
		<form class="create_task_form">
			<input type="text" name="title" placeholder="Ingrese una nueva tarea      + para asignar usuario" 
			class="new_task form-control">
			<input type="hidden" name="task_id" value="">
			<span class="glyphicon glyphicon-plus"></span>
		</form>
		<div class="filters ">
			<ul class="nav nav-tabs">
				<li role="presentation" class="active search_status" id="1">
					<a href="#">
  						<span class="change_status glyphicon glyphicon-record tooltipstered"></span>
						Abiertas
					</a>
				</li>
				<li role="presentation" class="search_status"  id="2">
					<a href="#">
			  			<span class="change_status glyphicon glyphicon-play-circle tooltipstered"></span>
						Empezadas
					</a>
				</li>
				<li role="presentation" class="search_status" id="3">
					<a href="#">
						<span class="glyphicon glyphicon-ok-circle tooltipstered"></span>
  						Hechas
					</a>
				</li>
				<li role="presentation" class="search_status">
					<a href="#">
						<span class="glyphicon glyphicon-ok-circle tooltipstered"></span>
  						Todas
					</a>
				</li>
			</ul>
  		</div>
		<ul class="tasks_list list-unstyled">
		</ul>
	</div>
</div>
<div class="detail_task">
	
</div>
<script type="text/javascript">
	var current_user_id = <?php echo (!empty($this->user) ? $this->user->getId() : '');?>;
	var current_user_name = '<?php echo (!empty($this->user) ? $this->user->getName() : '');?>';
</script>