<div id="index">
	<div class="menu_left nano">
			<div class="nano-content">
			<h1>MARCADOR DE TAREAS</h1>
			<div class="projects">
				<div class="user_logged">
					<div class="right">
					<?php if ($this->user != null):?>
						<a href="/task/usuario/profile" data-bypass="data-bypass">
					<?php if ($this->user->getFbKey()): ?>
						<img src="//graph.facebook.com/<?php echo $this->user->getFbKey();?>/picture" class="user_photo">
					<?php else: ?>
						<?php
						$image = $this->baseUrl . DIRECTORY_SEPARATOR .
						'../task_profiles' . DIRECTORY_SEPARATOR .
						$this->user->getId() . DIRECTORY_SEPARATOR .
						'profile.png';


	$path_image = Application_Config_Application::getProfilePath() . DIRECTORY_SEPARATOR . Application_Service_Session::getUser()->getId() . DIRECTORY_SEPARATOR . 'profile.png';


						if (file_exists($path_image)) : ?>
							<img src="<?php echo $image;	?>" class="user_photo">
						<?php else: ?>
							<?php echo $this->user->getName();?>
						<?php endif; ?>
					<?php endif; ?>
						</a>
					<a class="glyphicon glyphicon-off" href="/task/usuario/salir" data-bypass="data-bypass">
					</a>
					<?php endif;?>
					</div>
					<div class="clear"></div>
				</div>
				<div class="users_title" >
					Usuarios
					<span class="glyphicon glyphicon-plus btn" id="create_user" title="Crear usuario"></span>
				</div>
				<ul class="users_list">
				<?php foreach ($this->users as $user):?>
					<li>
						<a href="/task/index/index/project/undefined/status/1/user/<?php echo $user->getId();?>" class="user" value="<?php echo $user->getId();?>">
							<?php echo $user->getName();?>
						</a>
						<span class="badge openned"><?php echo $user->getLastModified();?></span>
						<a href="/task/index/index/edit_user/<?php echo $user->getId();?>" class="edit_user" value="<?php echo $user->getId();?>">
							<span class="right glyphicon glyphicon-edit"></span>
						</a>
					</li>
				<?php endforeach;?>
				</ul>
				<div class="project_title" >
					<a href="#" class="title_my_projects">Mis Proyectos</a>
					<span class="glyphicon glyphicon-plus" id="create_project" title="Crear Proyecto"></span>
					<a href="/task/project/gantt" data-bypass="data-bypass" title="Diagrama de Gantt"><span class="glyphicon fa fa-line-chart"></span></a>
				</div>
				<ul class="projects_list">
				<?php foreach ($this->projects as $project):?>
					<li>
						<a href="/task/index/index/<?php echo $project->getId();?>" class="project" value="<?php echo $project->getId();?>"><?php echo $project->getName();?></a>
						<?php $count_openned = $project->getCountOpenned();?>
						<?php if ($count_openned > 0) :?>
							<span class="badge openned"><?php echo $count_openned?></span>
						<?php else:?>
							<span class="badge closed"><?php echo $count_openned?></span>
						<?php endif;?>
						<a href="/task/index/index/<?php echo $project->getId();?>" class="edit_project" value="<?php echo $project->getId();?>"><span class="right glyphicon glyphicon-edit"></span></a>
					</li>
				<?php endforeach;?>
				</ul>
			</div>
		</div>
	</div>
	<div class="menu_right nano">
		<?php echo $this->partial('index/menuright.phtml', array()); ?>
	</div>
</div>
<div class="detail_task">
	
</div>

<script type="text/javascript">
	var current_user_id = <?php echo (!empty($this->user) ? $this->user->getId() : 'null');?>;
	var current_user_name = "<?php echo (!empty($this->user) ? $this->user->getName() : '');?>";
	var status_list = <?php echo (!empty($this->status) ? json_encode($this->status) : '[]'); ?>;
</script>
