<?php if (isset($this->task)) :?>
<?php echo $this->headLink()
              ->prependStylesheet($this->webApp . '/css/task/view.css');?>
	<div id="view_task">
		<?php $status = $this->task->getStatus();
		if ($status) {
			switch($status->getDescripcion()) {
				case 'Openned':
					$class = 'glyphicon-record';
					break;
				case 'Started':
					$class = 'glyphicon-play-circle';
					break;
				case 'Done':
					$class = 'glyphicon-ok-circle';
					break;
			}
		} else {
			$class = 'glyphicon-record';
		}?>
		<div>
		<a href="#" class="left show_status glyphicon <?php echo $class?>" value="<?php echo $this->task->getStatusId()?>" ></a>
		<form class="title_view_form left ">
			<textarea name="title" class="autosize" ><?php echo $this->task->getTitle();?></textarea>
		</form>
		<a href="#" class="remove glyphicon glyphicon-trash" value="<?php echo $this->task->getId()?>" ></a>
		</div>
		<div class="asign">
			<span>Asignados: </span>
			<?php $users = $this->task->getUsers();?>
			<?php echo implode(', ', $users);?>
		</div>
		<script type="text/javascript">
			$(document).ready(function() {
				setTimeout(function() {
						$('.autosize').autosize();
				},1000);
			});
		</script>
	</div>
<?php endif;?>