<?php if (isset($this->task)) :?>
<?php echo $this->headLink()
              ->prependStylesheet($this->webApp . '/css/task/view.css');?>
	<div id="view_task">
		<?php $status = $this->task->getStatus();
		if ($status) {
			switch($status->getDescripcion()) {
				case 'Openned':
					$class = 'glyphicon-record';
					break;
				case 'Started':
					$class = 'glyphicon-play-circle';
					break;
				case 'Done':
					$class = 'glyphicon-ok-circle';
					break;
			}
		} else {
			$class = 'glyphicon-record';
		}?>
		<div>
		<a href="#" class="left show_status glyphicon <?php echo $class?>" value="<?php echo $this->task->getStatusId()?>" ></a>
		<form class="title_view_form left ">
			<textarea name="title" class="autosize" ><?php echo $this->task->getTitle();?></textarea>
		</form>
		<a href="#" class="remove glyphicon glyphicon-trash" value="<?php echo $this->task->getId()?>" ></a>
		</div>
		<div class="asign">
			<span>
				Asignados:
			</span>
			<input type="text" name="asign" placeholder="Ingrese usuario" class="asign_user form-control">
			<?php $users = $this->task->getUsers();?>
			<ul class="user_asigned">
			<?php foreach ($users as $user):?>
				<li><?php echo $user;?></li>
			<?php endforeach;?>
			</ul>
		</div>
		<script type="text/javascript">
$(document).ready(function() {
	setTimeout(function() {
			$('.autosize').autosize();
	},1000);

	// AUTOCOMPLETE ASIGN USERS IN DETAILS
	$(".detail_task .asign_user").autocomplete({
		source : function(request, response) {

			discard = [];
			$('.user_asigned li').each(function(index,element) {
				discard[discard.length] = $(element).html();
			}); 
			$.ajax({
				url : base_url + '/usuario/search',
				data : {
					name : request.term,
					discard: discard
				},
				dataType : 'json',
				type : 'GET',
				success : function(data) {
					ultimos_buscados = data;
					response($.map(data, function(item) {
						return {
							label : item.name,
							value : item.id
						};
					}));
				},
				error : function(request, status, error) {
					alert(error);
				}
			});
		},
		minLength : 1,
		focus: function(event,ui) {
			return false;
		},
		select : function(event, ui) {
			abrir_cargando();

			$.post(
				base_url + '/task/asign', 
				{
					id : ultimo_selected_task,
					name: ui.item.label
				},
				'json'
			).done(function(response) {
				if (response) {
					$('.user_asigned').append('<li value="' + ui.item.id + '">' + ui.item.label + '</li>');
					$(".detail_task .asign_user").val('');
					$('.tasks_list li[value="'+ ultimo_selected_task + '"] .task_users').append(
						'<a href="#' + ui.item.id + '" class="right user">' + ui.item.label + '</a>'
					);
				}
			}).fail(function() {
				
			}).always(function() {
				cerrar_cargando();
			});;
			return false;
		},
		response : function(event, ui) {
		}
	});
	$(document).keyup(function(e){ 
		if(e.keyCode == 27) {
			$('.detail_task').animate({
				left: "slide",
			    width: "toggle",
			});
		}
	});
});
		</script>
	</div>
<?php endif;?>