<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Task</title>
      <?php echo $this->headLink()
              ->prependStylesheet($this->webApp . '/css/style.css')
              ->headLink(
                  array(
					'rel' => 'shortcut icon',
					'href' => $this->webApp . '/img/frio2.png'
                  ),
				  'PREPEND'
              );
              echo $this->headScript()
                  ->prependFile($this->webApp . '/js/main.js')
                  ->prependFile($this->webApp . '/js/libs.js');
              
      ?>
      <script type="text/javascript">
      	var base_url = '<?php echo $this->baseUrl;?>';
        var error = "<?php echo $this->error;?>";
        $(function() {

          if (error.length) {

            var dialog_error = $('<div>', {
              "html": error,
              "id": "dialog_error"
            });

            $('body').append(dialog_error);

            $('#dialog_error').dialog();
          }
        });
      </script>
    </head>
    <body>
		<div class="container contenedor">
			<?php echo $this->layout()->content;?>
		</div>
    </body>
</html>