<table class="table">
	<tr>
		<th>Proyecto</th>
		<th>Activo</th>
		<th>Fecha Inicio</th>
		<th>Fecha Fin</th>
	</tr>
<?php foreach ($this->projects as $project) : ?>
	<tr>
		<th><?php echo $project->getName();?></th>
		<td><input name="active" class="" type="checkbox" checked="<?php echo ($project->getCountOpenned() > 0 ? 'checked' : '');?>"></td>
		<td><input name="date_start" class="form-control datepicker" type="date" value="<?php echo $project->getDateStart(); ?>" /><td>
		<td><input name="date_end" class="form-control datepicker" type="date" value="<?php echo $project->getDateEnd(); ?>" /><td>
		<td><button class="btn btn-primary save" id="<?php echo $project->getId();?>">Guardar</button><td>
	</tr>
<?php endforeach; ?>
</table>
<a href="/task/" class="btn btn-primary" data-bypass="data-bypass">Listo</a>
<a href="/task/project/gantt" class="btn btn-primary" data-bypass="data-bypass">Gantt</a>
<?php echo $this->headScript()->prependFile($this->webApp . '/js/project/task.js'); ?>